# This file was generated by GoReleaser. DO NOT EDIT.
cask "grove-go" do
  version "0.13.1-go"

  on_macos do
    on_intel do
      url "https://github.com/nicksenap/grove/releases/download/v#{version}/gw_#{version}_darwin_amd64.tar.gz"
      sha256 "451cf799235231222811c64e3e6cbe226322995b5533b90c1877b666e2ed6b36"
    end
    on_arm do
      url "https://github.com/nicksenap/grove/releases/download/v#{version}/gw_#{version}_darwin_arm64.tar.gz"
      sha256 "3367f8f5423790859d8ba3641dcff3aaae643984e98d035eaf1c2ed6d3856100"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/nicksenap/grove/releases/download/v#{version}/gw_#{version}_linux_amd64.tar.gz"
      sha256 "89bed281a8ae80782327a57254a5a504d4a70faa4dafeae6dd5bd268b521ec5e"
    end
    on_arm do
      url "https://github.com/nicksenap/grove/releases/download/v#{version}/gw_#{version}_linux_arm64.tar.gz"
      sha256 "6960eccf7c8c87a1307aed301cb2a4feab9961daaa00f20fef1e2ce5a3cac5e5"
    end
  end

  name "grove-go"
  desc "Git Worktree Workspace Orchestrator (Go)"
  homepage "https://github.com/nicksenap/grove"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "gw"

  # No zap stanza required

end
