# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Grove < Formula
  desc "Git Worktree Workspace Orchestrator"
  homepage "https://github.com/nicksenap/grove"
  version "1.1.14"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/nicksenap/grove/releases/download/v1.1.14/gw_1.1.14_darwin_amd64.tar.gz"
      sha256 "ce0aaca45abd01d5dde66dd3b2e2b0bd025c9f0339214e755d24a08bfd8d9192"

      define_method(:install) do
        bin.install "gw"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/nicksenap/grove/releases/download/v1.1.14/gw_1.1.14_darwin_arm64.tar.gz"
      sha256 "a5cd878556274848176b1c7e9435ec4d8a737f0da515896c45e9c7f39dcfa938"

      define_method(:install) do
        bin.install "gw"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/nicksenap/grove/releases/download/v1.1.14/gw_1.1.14_linux_amd64.tar.gz"
      sha256 "ae5a48dc9ce8c6f1ef828775c8c842289f81cb61493b23d0b4938ad3ada18ada"
      define_method(:install) do
        bin.install "gw"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/nicksenap/grove/releases/download/v1.1.14/gw_1.1.14_linux_arm64.tar.gz"
      sha256 "b13d7d3e515a7d9a23b9b0a0c58441d25258ba1fc825d025099bd6d5024f1de9"
      define_method(:install) do
        bin.install "gw"
      end
    end
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/gw --version")
  end
end
