# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GroveGo < Formula
  desc "Git Worktree Workspace Orchestrator (Go)"
  homepage "https://github.com/nicksenap/grove"
  version "0.13.2-go"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/nicksenap/grove/releases/download/v0.13.2-go/gw_0.13.2-go_darwin_amd64.tar.gz"
      sha256 "637a081284b9643dc302208d00e350d06c68d6475c4491182a96b8944ebef35b"

      define_method(:install) do
        bin.install "gw"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/nicksenap/grove/releases/download/v0.13.2-go/gw_0.13.2-go_darwin_arm64.tar.gz"
      sha256 "ffb61c1f5eb173160d4f9d717b6a4feccd70aa5d55da50064eefffe4a08e3c2a"

      define_method(:install) do
        bin.install "gw"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/nicksenap/grove/releases/download/v0.13.2-go/gw_0.13.2-go_linux_amd64.tar.gz"
      sha256 "c8d11fea078c0fbc8d282b5b01a1ac1469631a7c5aa6ecde10d9c30daa69a538"
      define_method(:install) do
        bin.install "gw"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/nicksenap/grove/releases/download/v0.13.2-go/gw_0.13.2-go_linux_arm64.tar.gz"
      sha256 "e556a92f53e99d3740da9a5d2c06fa9b827aa128f57b6bacb7dd4e9a29e8bb5b"
      define_method(:install) do
        bin.install "gw"
      end
    end
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/gw --version")
  end
end
