# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GroveGo < Formula
  desc "Git Worktree Workspace Orchestrator (Go)"
  homepage "https://github.com/nicksenap/grove"
  version "0.13.5-go"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/nicksenap/grove/releases/download/v0.13.5-go/gw_0.13.5-go_darwin_amd64.tar.gz"
      sha256 "ceffaf0fa4c89ba1e35cb7aede5251004984b9e35f979174e21d2ff5764b7f30"

      define_method(:install) do
        bin.install "gw"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/nicksenap/grove/releases/download/v0.13.5-go/gw_0.13.5-go_darwin_arm64.tar.gz"
      sha256 "861150b97e7b6e8625690a2301294a255b5c62dbbb87f943a1e88a502972f40a"

      define_method(:install) do
        bin.install "gw"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/nicksenap/grove/releases/download/v0.13.5-go/gw_0.13.5-go_linux_amd64.tar.gz"
      sha256 "c91ec26c581c93e32a72a1f3c1fe1c216c2b096c9dbe60bc87036a526395642f"
      define_method(:install) do
        bin.install "gw"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/nicksenap/grove/releases/download/v0.13.5-go/gw_0.13.5-go_linux_arm64.tar.gz"
      sha256 "5f0fcb72caa2cae828dd1497a6909a18ed2f2239a4d59b81dfacf99d57f53b2a"
      define_method(:install) do
        bin.install "gw"
      end
    end
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/gw --version")
  end
end
