# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Grove < Formula
  desc "Git Worktree Workspace Orchestrator"
  homepage "https://github.com/nicksenap/grove"
  version "1.1.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/nicksenap/grove/releases/download/v1.1.1/gw_1.1.1_darwin_amd64.tar.gz"
      sha256 "917f854b12dc34cf249f44ade27526905da3dc49d75e54f830fa297f0f741a2a"

      define_method(:install) do
        bin.install "gw"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/nicksenap/grove/releases/download/v1.1.1/gw_1.1.1_darwin_arm64.tar.gz"
      sha256 "de377530738e5e81240c8ca13bff86019fc9a60d886249f63ddf0b364925f70b"

      define_method(:install) do
        bin.install "gw"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/nicksenap/grove/releases/download/v1.1.1/gw_1.1.1_linux_amd64.tar.gz"
      sha256 "a74d2c1d692d72e82a8c814b13538a3977045506b249b8267199122d2e779e3e"
      define_method(:install) do
        bin.install "gw"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/nicksenap/grove/releases/download/v1.1.1/gw_1.1.1_linux_arm64.tar.gz"
      sha256 "f6bd14f26b9ca17d2ce19871e96e01ba81192f0401fba751d5a608f8960dcefe"
      define_method(:install) do
        bin.install "gw"
      end
    end
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/gw --version")
  end
end
