# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Grove < Formula
  desc "Git Worktree Workspace Orchestrator"
  homepage "https://github.com/nicksenap/grove"
  version "1.0.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/nicksenap/grove/releases/download/v1.0.1/gw_1.0.1_darwin_amd64.tar.gz"
      sha256 "9964ade8b9d306746b1e5d78e234c48e1f2dea301a1e3a323fee5b1f14a6292e"

      define_method(:install) do
        bin.install "gw"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/nicksenap/grove/releases/download/v1.0.1/gw_1.0.1_darwin_arm64.tar.gz"
      sha256 "fe94c36a3960cfb8706634b984d58ed0c7f96d3e4793a5293e4734ab4588f123"

      define_method(:install) do
        bin.install "gw"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/nicksenap/grove/releases/download/v1.0.1/gw_1.0.1_linux_amd64.tar.gz"
      sha256 "37f9bcf25a7860536bced1aa3cf6a44a83a44491ed728e3832756b067bde8f2e"
      define_method(:install) do
        bin.install "gw"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/nicksenap/grove/releases/download/v1.0.1/gw_1.0.1_linux_arm64.tar.gz"
      sha256 "1d7f73961b074693cfcb8c8da2039d14bceef97f80a965af5bf26856396e4c1e"
      define_method(:install) do
        bin.install "gw"
      end
    end
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/gw --version")
  end
end
